spring.application.name=Taxi-Moto-App_backend

server.address=0.0.0.0

server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/motoTaxi_db
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
mapbox.access-token=sk.eyJ1Ijoic2FsbWVuLW90YXk5NiIsImEiOiJjbW5yd3hleXIwNmF6MnBzNmMzdTJmaDN1In0.Lqvm0hkiZPi1nmN0Wi_zwg



# ================= JWT =================
jwt.secret=MaCleSecreteTresLongueEtSecurisee12345
jwt.expiration-ms=3600000   # 1 heure en millisecondes


# ================= SPRING SECURITY =================
spring.security.user.name=admin
spring.security.user.password=admin123